import assert from 'node:assert/strict';
import * as M from '../lab/mir/modulation/mod.js';
M.modReset();
const m=M.addMacro(null); M.setMacro(m.id,{value:.5});
const r=M.addRoute(m.id,'test',0,.4).route;
assert.equal(M.targetValue('test',.25,false),.45);
M.setRouteRange(r.id,{curve:1});
assert.equal(M.targetValue('test',.25,false),.275);
M.setRouteRange(r.id,{enabled:false});
assert.ok(Number.isNaN(M.targetValue('test',.25,false)));
assert.equal(M.targetPos('test',.25,false),null);
const saved=M.serialize(); M.modReset(); M.deserialize(saved);
const restored=M.routeList()[0];
assert.equal(restored.curve,1);assert.equal(restored.enabled,false);
M.setRouteRange(restored.id,{enabled:true,curve:0,bi:true});
M.setMacro(restored.macroId,{value:0});
assert.ok(Math.abs(M.targetValue('test',.25,false)-.05)<1e-15);
M.setMacro(restored.macroId,{value:1});
assert.equal(M.targetValue('test',.25,false),.45);
M.setRouteRange(restored.id,{bi:false,min:.4,max:0});
assert.ok(Math.abs(M.targetValue('test',.5,false)-.1)<1e-15);
assert.ok(M.modStateReadable(104) && M.modStateReadable(105));
console.log('PASS Final II: signed amount, bipolar anchoring, curve, bypass, and persistence');
