# bf-r4-corpus.py — Round 4 (Opus).  Three corpus bridges, with numbers.
#
# BRIDGE 1 (YMD-DISK-01 COMPENDIUM, Y-0138 / lines 519-590).  The corpus's Yang-Mills gap programme measures
#   sigma_0(beta) = -log(I_2(beta)/I_1(beta)) = sum_k s_k beta^{-k},  s = 3/2, 3/4, 3/16, -9/16,
#   Gevrey-1 with |s_k/s_{k-1}|/k -> 0.49 and Borel singularity "A = 2.0027" (Richardson [1.95,2.03], Borel-Pade 2.26).
# The late-term calculus of Round-4 section 1.1 settles it EXACTLY.  The same triplication trick that gave
#   u_k = Gamma(k+1/6)Gamma(k+5/6)/(2 pi 2^k Gamma(k+1))  for Airy gives, for the Bessel series,
#   a_k(nu) = (-1)^k cos(pi nu)/pi * Gamma(k+nu+1/2) Gamma(k-nu+1/2) / (Gamma(k+1) 2^k)   [reflection formula]
# hence  Gcal_{I_nu} = (cos pi nu / pi) * Kcal_nu ,  singulant chi = +2 (POSITIVE: e^{-2 beta} is small on R^+,
# so unlike the revival series this one IS non-Borel-summable on the positive axis), and
#   Gcal_sigma0 = -(1/pi)[ Kcal_1/Ical_1 + Kcal_2/Ical_2 ] = -(2/pi)(1 + (9/4)x + ...)
#   =>  s_k = -(2/pi) [ Gamma(k)/2^k + (9/4) Gamma(k-1)/2^{k-1} + ... ],  i.e. A = 2 EXACTLY, S = -2/pi, c1 = 9/2.
#
# BRIDGE 2 (Q23).  The Schmidt-spectrum obstruction is an so(4) statement, not a "shell operator" statement:
#   e^{i alpha L^2} is generated by J_+ . J_- (an ENTANGLING gate between the two rotors), lives inside the shell,
#   and reaches the Stark state from 2s.  Fable's proposed theorem is refuted by an explicit unitary.
#
# BRIDGE 3 (Q21).  The coherent-state dictionary, with the (n-1)/n that Round 3's guess drops.
import math, cmath
from fractions import Fraction as F
import numpy as np
import mpmath as mp
mp.mp.dps = 60

print('=' * 96)
print('BRIDGE 1 — YMD-DISK-01 Y-0138: sigma_0(beta) = -log(I_2/I_1).  Exact Stokes data.')
print('=' * 96)
N = 60
def a(k, nu):                       # a_k(nu) = prod_{j=1}^k (4nu^2 - (2j-1)^2) / (k! 8^k)
    p = F(1)
    for j in range(1, k + 1):
        p *= F(4 * nu * nu - (2 * j - 1) ** 2)
    for j in range(1, k + 1):
        p /= j
    return p / F(8) ** k
def mul(u, v, N):
    c = [F(0)] * (N + 1)
    for i, x in enumerate(u):
        if x == 0: continue
        for j, y in enumerate(v):
            if i + j > N: break
            if y: c[i + j] += x * y
    return c
def inv(u, N):
    b = [F(0)] * (N + 1); b[0] = 1 / u[0]
    for n in range(1, N + 1):
        b[n] = -sum(u[k] * b[n - k] for k in range(1, n + 1)) / u[0]
    return b
def logser(u, N):
    ui = inv(u, N); d = [F(k) * u[k] for k in range(1, N + 1)] + [F(0)]
    da = mul(d, ui, N)
    return [F(0)] + [da[k - 1] / k for k in range(1, N + 1)]
I1 = [(-1) ** k * a(k, 1) for k in range(N + 1)]
I2 = [(-1) ** k * a(k, 2) for k in range(N + 1)]
K1 = [a(k, 1) for k in range(N + 1)]
K2 = [a(k, 2) for k in range(N + 1)]
L1, L2 = logser(I1, N), logser(I2, N)
s = [L1[k] - L2[k] for k in range(N + 1)]           # sigma_0 = log I1 - log I2   (the prefactors cancel exactly)
print('  s_1..s_6 (exact) =', [str(x) for x in s[1:7]], '   corpus (Y-0138): 3/2, 3/4, 3/16, -9/16')
# exact closed form check for a_k(nu)
ok = all(abs(mp.mpf(a(k, nu).numerator) / mp.mpf(a(k, nu).denominator)
             - (-1) ** k * mp.cos(mp.pi * nu) / mp.pi * mp.gamma(k + nu + mp.mpf(1)/2) * mp.gamma(k - nu + mp.mpf(1)/2)
             / (mp.gamma(k + 1) * mp.mpf(2) ** k)) < mp.mpf('1e-40') * abs(mp.mpf(a(k, nu).numerator) / mp.mpf(a(k, nu).denominator) + 1)
         for nu in (1, 2, 3) for k in range(1, 20))
print(f'  closed form  a_k(nu) = (-1)^k cos(pi nu)/pi * G(k+nu+1/2)G(k-nu+1/2)/(G(k+1) 2^k)  verified: {ok}')
# late-term prediction:  Gcal_sigma0 = -(1/pi)(Kcal_1/Ical_1 + Kcal_2/Ical_2)
G = [-(mul(K1, inv(I1, N), N)[k] + mul(K2, inv(I2, N), N)[k]) for k in range(N + 1)]   # times 1/pi
print('  Gcal_sigma0(x) = (1/pi) *', [str(G[k]) for k in range(4)], '   => S = -2/pi, first correction c1 = 9/2')
print('  large-order test:   s_k * 2^k / Gamma(k)   should -> -2/pi = -0.63661977')
print('     k        s_k 2^k/Gamma(k)      full dictionary ratio (8 terms)')
for k in [5, 10, 20, 30, 40, 50, 60]:
    sk = mp.mpf(s[k].numerator) / mp.mpf(s[k].denominator)
    lead = sk * mp.mpf(2) ** k / mp.gamma(k)
    pred = sum(mp.mpf(G[r].numerator) / mp.mpf(G[r].denominator) / mp.pi * mp.gamma(k - r) / mp.mpf(2) ** (k - r)
               for r in range(min(8, k - 1)))
    print(f'   {k:4d}   {mp.nstr(lead, 12):>18s}      {mp.nstr(sk / pred, 12)}')
rat = [abs(mp.mpf(s[k].numerator)/mp.mpf(s[k].denominator) / (mp.mpf(s[k-1].numerator)/mp.mpf(s[k-1].denominator))) / k
       for k in range(2, N + 1)]
print(f'  |s_k/s_(k-1)|/k at k = 4, 10, 30, 60 : {[mp.nstr(rat[k-2],8) for k in (4,10,30,60)]}   -> 1/2 EXACTLY '
      f'(corpus reported 0.49 from four terms)')
print('  => Y-0138\'s Borel singularity A = 2.0027 (Richardson) / 2.26 (Borel-Pade) is EXACTLY A = 2,')
print('     and the Stokes constant of sigma_0 is exactly -2/pi with first correction 9/2.')

print()
print('=' * 96)
print('BRIDGE 2 — Q23: an explicit IN-SHELL unitary that reaches the Stark state from 2s (refutes the proposed theorem)')
print('=' * 96)
# n = 2 shell, basis |2s>, |2p_0>, |2p_+>, |2p_->; K_z acts as sigma_x on {2s, 2p_0} (Pauli), 0 on m = +-1.
# The su(2)xsu(2) (= so(4)) group acts as C -> g1 C g2^T on the 2x2 Clebsch matrix: singular values invariant.
Cs = np.array([[0, 1], [-1, 0]]) / math.sqrt(2)          # |2s>   = singlet
Cp = np.array([[0, 1], [1, 0]]) / math.sqrt(2)           # |2p_0> = triplet m=0
print('  Schmidt spectra:  2s ->', np.round(np.linalg.svd(Cs, compute_uv=False), 12),
      '   Stark (2s-2p0)/sqrt2 ->', np.round(np.linalg.svd((Cs - Cp) / math.sqrt(2), compute_uv=False), 12))
# The so(4) rotor alone:
th = math.pi / 4
psi = np.array([math.cos(th), -1j * math.sin(th)])       # e^{-i th K_z}|2s> in the (2s, 2p0) basis
z_me = -3.0                                              # <2s|z|2p0> = -3 (Round 2 section 4.1)
print(f'  e^(-i pi/4 K_z)|2s> = {psi.round(6)}   <z> = {2*(np.conj(psi[0])*psi[1]).real*z_me:+.10f}  (Round 2: identically 0)')
# now add the L^2 phase (l-dependent), alpha = pi/4:  |2p0> picks up e^{2 i alpha} = i
psi2 = np.array([psi[0], psi[1] * cmath.exp(1j * 2 * (math.pi / 4))])
print(f'  e^(i pi/4 L^2) e^(-i pi/4 K_z)|2s> = {psi2.round(10)}   <z> = {2*(np.conj(psi2[0])*psi2[1]).real*z_me:+.10f}'
      f'   (= the Stark value -3)')
Cnew = (psi2[0] * Cs + psi2[1] * Cp)
print('  its Schmidt spectrum =', np.round(np.linalg.svd(Cnew, compute_uv=False), 12), ' -> rank 1: the orbit HAS changed.')
print('  L^2 = (J_+ + J_-)^2 = 2 j(j+1)*2 + 2 J_+ . J_- : an ENTANGLING generator between the two rotors,')
print('  physically the quantum defect (any l-dependent energy).  It is a shell operator and it is unitary.')

print()
print('=' * 96)
print('BRIDGE 3 — Q21: the SO(4) coherent-state dictionary, with the (n-1)/n Round 3 dropped')
print('=' * 96)
print('  |j n_+> (x) |j n_-> :  <L> = j(n_+ + n_-),  <K> = j(n_+ - n_-),  j = (n-1)/2')
print('  |<L>| = (n-1) cos(gamma/2),  |<K>| = (n-1) sin(gamma/2),  |<L>|^2 + |<K>|^2 = (n-1)^2  (NOT n^2, NOT n^2-1)')
print('  classical Kepler at energy E_n:  K = A/sqrt(-2E) = n A,  so  e = |A| = |<K>|/n = ((n-1)/n) sin(gamma/2)')
print('  and  |<L>| = n sqrt(1-e^2) * (n-1)/n ... i.e. the classical identity L^2 = n^2(1-e^2) holds only up to ((n-1)/n)^2.')
print('   n    j     e(circular)   e(extreme Stark)   |<z>|max = 3n(n-1)/2   a = n^2')
for n in (2, 3, 4, 6, 10, 30):
    print(f'  {n:3d}  {(n-1)/2:4.1f}      0.0            {(n-1)/n:.6f}            {1.5*n*(n-1):8.1f}          {n*n:5d}')
print('  Round 3 wrote "e = |K|/sqrt(L^2+K^2)" and "extreme Stark: e = 1".  Both are the gamma -> pi limit of')
print('  sin(gamma/2) = 1 WITHOUT the (n-1)/n: the true extreme-Stark eccentricity is (n-1)/n, = 1/2 at n = 2,')
print('  2/3 at n = 3, 5/6 at n = 6.  No hydrogenic state has a degenerate (radial) Kepler orbit.')
