# bf-r4-stokes.py — Round 4 (Opus). Q19 settled: the sign convention, the constant 1/(6 pi e), and c = 7/9.
#
# Three independent pieces:
#  (1) EXACT closed form for the Airy coefficients:  u_k = (1/6)_k (5/6)_k / (k! 2^k)
#      equivalently u_k = Gamma(k+1/6) Gamma(k+5/6) / (2 pi 2^k Gamma(k+1)).   [triplication formula]
#      => the Borel transform of the Airy series is a 2F1 with a SIMPLE POLE of residue -1/(2 pi)
#      at tau = -2 (for the alternating series U), so chi_x = -2  (NEGATIVE: the adjacent
#      exponential is e^{+2 zeta}, i.e. Bi, not e^{-2 zeta}).  This is the sign Round 3 could not settle.
#  (2) LATE-TERM CALCULUS carried through the whole chain exactly (Fractions), giving
#      C_k ~ sum_r  Gcal_r  Gamma(k-r) / chi_W^{k-r},   chi_W = -1/54,  Gcal(W) = (1/(6 pi e))(1 + 42 W + ...)
#      => C_k = (-1)^k 54^k Gamma(k)/(6 pi e) * (1 - (7/9)/(k-1) + O(k^-2)).
#  (3) NUMERICAL CHECK: C_k to high order by LAGRANGE INVERSION (fast), fitted against (2).
import sys
from fractions import Fraction as F
import mpmath as mp

R = int(sys.argv[1]) if len(sys.argv) > 1 else 8      # order of the late-term series Gcal
NC = int(sys.argv[2]) if len(sys.argv) > 2 else 110   # how many C_k to compute numerically
mp.mp.dps = 320

# ---------- truncated power series over Fractions ----------
def mul(a, b, N):
    c = [F(0)] * (N + 1)
    for i, x in enumerate(a):
        if x == 0 or i > N: continue
        for j, y in enumerate(b):
            if i + j > N: break
            if y: c[i + j] += x * y
    return c
def inv(a, N):
    b = [F(0)] * (N + 1); b[0] = 1 / a[0]
    for n in range(1, N + 1):
        b[n] = -sum(a[k] * b[n - k] for k in range(1, n + 1) if k < len(a)) / a[0]
    return b
def compose(g, z, N):        # g(z(w)), requires z[0]==0
    out = [F(0)] * (N + 1); p = [F(0)] * (N + 1); p[0] = F(1)
    for k in range(N + 1):
        if k: p = mul(p, z, N)
        if all(x == 0 for x in p): break
        for i in range(N + 1):
            if g[k]: out[i] += g[k] * p[i]
    return out
def expser(a, N):            # exp(a), a[0]==0
    out = [F(0)] * (N + 1); out[0] = F(1)
    for n in range(1, N + 1):     # out' = a' out
        out[n] = sum(F(k, n) * a[k] * out[n - k] for k in range(1, n + 1))
    return out
def logser(a, N):            # log(a), a[0]==1
    ai = inv(a, N); d = [F(k) * a[k] for k in range(1, N + 1)] + [F(0)]
    da = mul(d, ai, N)
    return [F(0)] + [da[k - 1] / k for k in range(1, N + 1)]
def scale(a, s, N):          # a(s*x)
    return [a[k] * s ** k for k in range(N + 1)]
def powr(a, e, N):           # a^e for integer e, a[0]==1
    if e >= 0:
        r = [F(0)] * (N + 1); r[0] = F(1)
        b = a[:]; ee = e
        while ee:
            if ee & 1: r = mul(r, b, N)
            b = mul(b, b, N); ee >>= 1
        return r
    return powr(inv(a, N), -e, N)

N = R + 4
# ---------- (1) the Airy coefficients, exact ----------
u = [F(1)]
for k in range(1, N + 3):
    u.append(u[-1] * F((6 * k - 1) * (6 * k - 3) * (6 * k - 5), 216 * k * (2 * k - 1)))
# check the closed form u_k = (1/6)_k (5/6)_k /(k! 2^k)
ok = True
for k in range(1, N + 3):
    num = F(1)
    for j in range(k):
        num *= (F(1, 6) + j) * (F(5, 6) + j)
    cf = num / (F(2) ** k)
    for j in range(1, k + 1): cf /= j
    if cf != u[k]: ok = False
print(f'[1] u_k = (1/6)_k (5/6)_k / (k! 2^k) exact for k<= {N+2}: {ok}')
print(f'    u_k = Gamma(k+1/6)Gamma(k+5/6)/(2 pi 2^k Gamma(k+1)); numeric check k=1..4:',
      [mp.nstr(mp.gamma(k + mp.mpf(1)/6) * mp.gamma(k + mp.mpf(5)/6) / (2*mp.pi*2**k*mp.gamma(k+1)) /
               mp.mpf(u[k].numerator) * mp.mpf(u[k].denominator), 12) for k in range(1, 5)])
v = [F(1)] + [-F(6 * k + 1, 6 * k - 1) * u[k] for k in range(1, N + 3)]

# ---------- (2) the late-term calculus ----------
# series in x = 1/zeta.  U0 = sum (-1)^k u_k x^k, V0 = sum (-1)^k v_k x^k.
U0 = [(-1) ** k * u[k] for k in range(N + 1)]
V0 = [(-1) ** k * v[k] for k in range(N + 1)]
# late-term data (chi_x = -2):  Gcal_U = (1/2pi) * Utilde,  Gcal_V = -(1/2pi) * Vtilde
# (Ai's late terms are generated by Bi's series; Ai''s by Bi''s.  Residue -1/(2pi) proved in [1].)
# we carry the rational part only; the overall 1/(2 pi) is restored at the end.
gU = [u[k] for k in range(N + 1)]
gV = [-v[k] for k in range(N + 1)]
h0 = mul(U0, inv(V0, N), N)                                  # h = U/V, formal, in x
gh = mul(inv(V0, N), [gU[k] - mul(h0, gV, N)[k] for k in range(N + 1)], N)
print('[2] h0(x)  =', [str(c) for c in h0[:4]])
print('    Gcal_h(x) = (1/2pi) *', [str(c) for c in gh[:4]])
# x = (3/2) y
hh = scale(h0, F(3, 2), N)                                   # hhat(y)
ghh = scale(gh, F(3, 2), N)
chi_y = F(-4, 3)
# formal solution h(w) of h = hhat(w h^{-3}) -- fixed point, cheap at this order
hw = [F(0)] * (N + 1); hw[0] = F(1)
for _ in range(N + 2):
    yw = [F(0)] + powr(hw, -3, N)[:N]                        # y = w h^{-3}
    hw = compose(hh, yw, N)
yw = [F(0)] + powr(hw, -3, N)[:N]
print('    h(w)   =', [str(c) for c in hw[:5]])
# E(w) = exp( chi_y*(1/w - 1/y) ) = exp( chi_y * (1/w)(1 - 1/phi) ),  y = w*phi
phi = powr(hw, -3, N)
one_minus_invphi = [(F(1) if k == 0 else F(0)) - inv(phi, N)[k] for k in range(N + 1)]
assert one_minus_invphi[0] == 0
arg = [chi_y * one_minus_invphi[k + 1] for k in range(N)] + [F(0)]     # chi_y*(1-1/phi)/w
const = arg[0]                                                # should be -1
Er = expser([F(0)] + arg[1:N + 1], N)                         # exp of the non-constant part
print(f'    exponent constant chi_y*(3/4) = {const}   (=> factor e^({const}))')
# D(w) = 1 + 3 w h^{-4} hhat'(y)
dhh = [F(k + 1) * hh[k + 1] for k in range(N)] + [F(0)]
D = [(F(1) if k == 0 else F(0)) for k in range(N + 1)]
tmp = mul(mul([F(0), F(3)] + [F(0)] * (N - 1), powr(hw, -4, N), N), compose(dhh, yw, N), N)
D = [D[k] + tmp[k] for k in range(N + 1)]
gh_w = mul(Er, mul(compose(ghh, yw, N), inv(D, N), N), N)     # times e^{const}/(2 pi)
gh2 = mul([F(2) * c for c in hw], gh_w, N)                    # Gcal_{h^2} = 2 h Gcal_h
gC = scale([c / 12 for c in gh2], F(72), N)                   # in W = beta^2 ; times e^{-1}/(2 pi)
chi_W = F(-1, 54)
print('    Gcal_C(W) = (1/(2 pi e)) * [', ', '.join(str(c) for c in gC[:R + 1]), ']')
print(f'    leading: 1/(2 pi e) * {gC[0]} = 1/({1/gC[0]} pi e)')
print(f'    C_k ~ S (-54)^k Gamma(k) [ 1 + sum_r (gC_r/gC_0) chi_W^r / ((k-1)...(k-r)) ]')
print(f'    r=1 term: (gC_1/gC_0)*chi_W = {gC[1]/gC[0]*chi_W}  -> c = {-gC[1]/gC[0]*chi_W}')
ratios = [gC[r] / gC[0] * chi_W ** r for r in range(R + 1)]
print('    dictionary coefficients b_r = (gC_r/gC_0)*chi_W^r :', [str(x) for x in ratios])

# ---------- (3) C_k numerically, by Lagrange inversion ----------
# w(y) = y * hhat(y)^3  =>  h(w)^2 = hhat(y(w))^2, and  [w^k] hhat(y)^2 = (1/k)[y^{k-1}] ( d(hhat^2)/dy * hhat^{-3k} )
M = NC + 2
hhf = [mp.mpf(c.numerator) / mp.mpf(c.denominator) for c in
       scale(mul(mul(U0, inv(V0, M if M <= N else N), N), [F(1)] + [F(0)] * N, N), F(3, 2), N)[:N + 1]]
# need hhat to order M: recompute the exact series to order M in mpf
def mulf(a, b, N):
    c = [mp.mpf(0)] * (N + 1)
    for i, x in enumerate(a):
        if x == 0 or i > N: continue
        for j, y in enumerate(b):
            if i + j > N: break
            if y: c[i + j] += x * y
    return c
def invf(a, N):
    b = [mp.mpf(0)] * (N + 1); b[0] = 1 / a[0]
    for n in range(1, N + 1):
        b[n] = -sum(a[k] * b[n - k] for k in range(1, n + 1) if k < len(a)) / a[0]
    return b
def logf(a, N):
    ai = invf(a, N); d = [mp.mpf(k) * a[k] for k in range(1, N + 1)] + [mp.mpf(0)]
    da = mulf(d, ai, N)
    return [mp.mpf(0)] + [da[k - 1] / k for k in range(1, N + 1)]
def expf(a, N):
    out = [mp.mpf(0)] * (N + 1); out[0] = mp.mpf(1)
    for n in range(1, N + 1):
        out[n] = sum(mp.mpf(k) / n * a[k] * out[n - k] for k in range(1, n + 1))
    return out
uf = [mp.mpf(1)]
for k in range(1, M + 2):
    uf.append(uf[-1] * mp.mpf((6*k-1)*(6*k-3)*(6*k-5)) / mp.mpf(216*k*(2*k-1)))
vf = [mp.mpf(1)] + [-mp.mpf(6*k+1)/mp.mpf(6*k-1)*uf[k] for k in range(1, M + 2)]
U0f = [(-1)**k * uf[k] for k in range(M + 1)]
V0f = [(-1)**k * vf[k] for k in range(M + 1)]
h0f = mulf(U0f, invf(V0f, M), M)
hhatf = [h0f[k] * mp.mpf(3)**k / mp.mpf(2)**k for k in range(M + 1)]     # hhat(y) = h0(3y/2)
L = logf(hhatf, M)                                                        # log hhat
hh2 = mulf(hhatf, hhatf, M)
dhh2 = [mp.mpf(k + 1) * hh2[k + 1] for k in range(M)] + [mp.mpf(0)]
C = []
for k in range(1, NC + 1):
    P = expf([-3 * k * L[j] for j in range(k)] + [mp.mpf(0)] * (M + 1 - k), k - 1)   # hhat^{-3k} to order k-1
    s = sum(dhh2[j] * P[k - 1 - j] for j in range(k))
    h2k = s / k                                                            # [w^k] h^2
    C.append(h2k * mp.mpf(72) ** k / 12)
print('[3] C_1..C_6 =', [mp.nstr(c, 12) for c in C[:6]], ' (exact: -3, 54, -4860, 769824, -169746192, 47259985248)')
S = 1 / (6 * mp.pi * mp.e)
print(f'    S = 1/(6 pi e) = {mp.nstr(S, 15)}')
print('      k     C_k/((-54)^k Gamma(k))      (S_k/S - 1)*(k-1)        (S_k/S-1)*(k-1) + 7/9')
seq = []
for k in [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, NC]:
    if k > len(C): continue
    Sk = C[k - 1] / ((mp.mpf(-54)) ** k * mp.gamma(k))
    d = (Sk / S - 1) * (k - 1)
    seq.append((k, Sk, d))
    print(f'   {k:5d}   {mp.nstr(Sk,14)}   {mp.nstr(d,12)}   {mp.nstr(d + mp.mpf(7)/9, 8)}')
# full Richardson on (S_k/S - 1)*(k-1) -> -7/9
allseq = [ (C[k-1]/((mp.mpf(-54))**k*mp.gamma(k))/S - 1)*(k-1) for k in range(1, len(C)+1) ]
def rich(s, p):
    return [((k+2)**p*s[k+1] - (k+1)**p*s[k])/((k+2)**p - (k+1)**p) for k in range(len(s)-1)]
r = allseq[5:]
for p in range(1, 6):
    r = rich(r, p)
    print(f'    Richardson-{p} tail: {[mp.nstr(x,12) for x in r[-3:]]}')
print(f'    target -7/9 = {mp.nstr(-mp.mpf(7)/9, 12)}')
# and the full dictionary prediction, all r
print('    full dictionary check:  C_k / [ S * sum_r b_r Gamma(k-r)/chi^{k-r} ]  should -> 1')
br = [mp.mpf(x.numerator)/mp.mpf(x.denominator) for x in [gC[r]/gC[0] for r in range(R+1)]]
chiW = -mp.mpf(1)/54
for k in [20, 40, 60, 80, 100, NC]:
    if k > len(C): continue
    pred = S * sum(br[r] * mp.gamma(k - r) / chiW ** (k - r) for r in range(min(R+1, k-1)))
    print(f'      k={k:4d}   ratio = {mp.nstr(C[k-1]/pred, 14)}')
