# bf-r5-lie.py — Round 5 (Fable), Q29: is the Lie algebra generated by so(4) = su(2)_+ ⊕ su(2)_- (the shell's rotors) and the
#   DEFECT WAIT generator L² = (J_+ + J_-)² all of su(n²)?  The shell is V_j ⊗ V_j, j = (n−1)/2; J_+ = j ⊗ 1, J_- = 1 ⊗ j.
#   Lie closure by repeated commutators with an orthonormal basis (real inner product Re tr(A†B)); identity projected out.
import sys
import numpy as np
def spin(j):
    d = int(round(2 * j + 1)); ms = np.array([j - k for k in range(d)])
    Jz = np.diag(ms).astype(complex)
    Jp = np.zeros((d, d), dtype=complex)
    for k in range(1, d):
        m = ms[k]; Jp[k - 1, k] = np.sqrt(j * (j + 1) - m * (m + 1))
    Jm = Jp.conj().T
    return (Jp + Jm) / 2, (Jp - Jm) / (2j), Jz
def closure(gens, tol=1e-9, maxdim=None):
    d = gens[0].shape[0]; I = np.eye(d)
    basis = []                                       # orthonormal anti-Hermitian matrices, traceless
    def add(A):
        A = (A - A.conj().T) / 2
        A = A - np.trace(A) / d * I
        for Bm in basis: A = A - np.real(np.vdot(Bm, A)) * Bm
        nrm = np.sqrt(np.real(np.vdot(A, A)))
        if nrm > tol:
            basis.append(A / nrm); return True
        return False
    for g in gens: add(g)
    frontier = list(basis)
    while frontier:
        new = []
        for A in frontier:
            for Bm in list(basis):
                C = A @ Bm - Bm @ A
                if add(C): new.append(basis[-1])
                if maxdim and len(basis) >= maxdim: return len(basis)
        frontier = new
    return len(basis)
for n in [2, 3, 4, 5]:
    j = (n - 1) / 2
    Jx, Jy, Jz = spin(j); d = int(round(2 * j + 1)); I = np.eye(d)
    Jp = [np.kron(A, I) for A in (Jx, Jy, Jz)]; Jm = [np.kron(I, A) for A in (Jx, Jy, Jz)]
    L2 = sum((a + b) @ (a + b) for a, b in zip(Jp, Jm))
    gens = [1j * A for A in Jp + Jm] + [1j * L2]
    dim = closure(gens, maxdim=n ** 4)
    dim_so4 = closure([1j * A for A in Jp + Jm])
    print(f'n = {n} (shell dim {n * n}): dim Lie⟨so(4), L²⟩ = {dim}  vs dim su(n²) = {n ** 4 - 1}   [so(4) alone: {dim_so4}]   → {"UNIVERSAL" if dim == n ** 4 - 1 else "NOT universal"}')
# the alternative entangler: K_z alone with L² (one rotor axis + the wait) — is even that enough?
for n in [2, 3]:
    j = (n - 1) / 2
    Jx, Jy, Jz = spin(j); d = int(round(2 * j + 1)); I = np.eye(d)
    Jp = [np.kron(A, I) for A in (Jx, Jy, Jz)]; Jm = [np.kron(I, A) for A in (Jx, Jy, Jz)]
    L = [a + b for a, b in zip(Jp, Jm)]; K = [a - b for a, b in zip(Jp, Jm)]
    L2 = sum(a @ a for a in L)
    dim = closure([1j * L[2], 1j * K[2], 1j * L[0], 1j * L2], maxdim=n ** 4)
    print(f'n = {n}: dim Lie⟨L_z, L_x, K_z, L²⟩ = {dim} vs {n ** 4 - 1}')
